apiVersion: v1
kind: Service
metadata:
  namespace: ns-sonarqube
  labels:
    name: sonar
  name: sonar
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      name: sonarport
  selector:
    name: sonarqube