kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ns-sonarqube
  name: claim-postgres
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
