apiVersion: v1
kind: Namespace
metadata:
  name: ns-ecr-renew
  labels:
    name: ns-ecr-renew
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ns-ecr-renew
  name: svc-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns-ecr-renew
  name: cr-ecr-renew
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ecr-docker-login"]
    verbs: ["get","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ns-ecr-renew
  name: rb-ecr-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew