   
- hosts: k8smaster
  user: cloudadmin
  become: true
  tasks:
  
    - name: Setup kube-sec Namespace. Use log to prevent second installation
     shell: kubectl apply -f https://raw.githubusercontent.com/F1re4fect/my-k8s/master/kube/kube-sec/kube-sec-namespace.yml >> kube-sec-ns.log
     args:
       chdir: $HOME
       creates: kube-sec-ns.log
  
   - name: Setup kube-hunter Job. Use log to prevent second installation
     shell: kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-hunter/master/job.yaml --namespace=kube-sec >> kube-hunter.log
     args:
       chdir: $HOME
       creates: kube-hunter.log
   - name: Setup kube-bench Job. Use log to prevent second installation
     shell: kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/master/job.yaml --namespace=kube-sec >> kube-bench.log
     args:
       chdir: $HOME
       creates: kube-bench.log
